name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0-59/30 00-06 * * *
    - cron: 0-59/30 21-23 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Generate index.html
        run: python mlb_stats.py --template

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
